### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jinjor** [jinjor/elm-video-chat#15]
```
TypeError: Cannot read property 'split' of undefined
    at Object.getUser (C:\Elm-Project\elm-video-chat\server\storage.js:31:13)
    at C:\Elm-Project\elm-video-chat\server\rest.js:19:15
    at Layer.handle [as handle_request] (C:\Elm-Project\elm-video-chat\node_modules\express\lib\rout
er\layer.js:82:5)
    at next (C:\Elm-Project\elm-video-chat\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (C:\Elm-Project\elm-video-chat\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (C:\Elm-Project\elm-video-chat\node_modules\express\lib\rout
er\layer.js:82:5)
    at C:\Elm-Project\elm-video-chat\node_modules\express\lib\router\index.js:267:22
    at param (C:\Elm-Project\elm-video-chat\node_modules\express\lib\router\index.js:340:14)
    at param (C:\Elm-Project\elm-video-chat\node_modules\express\lib\router\index.js:356:14)
    at Function.proto.process_params (C:\Elm-Project\elm-video-chat\node_modules\express\lib\router\
index.js:400:3)
```

**Comment by jinjor** [comment]
temporary added workaround
